# Define a dictionary for book information
BOOK_INFO = {
    "01": {"de": "Matt", "en": "Matt"},
    "02": {"de": "Mark", "en": "Mark"},
    "03": {"de": "Luk", "en": "Luke"},
    "04": {"de": "Joh", "en": "John"},
    "05": {"de": "Apg", "en": "Acts"},
    "06": {"de": "", "en": "Rom"},
    "07": {"de": "1.Kor", "en": "1.Cor"},
    "08": {"de": "2.Kor", "en": "2.Cor"},
    "09": {"de": "", "en": "Gal"},
    "10": {"de": "", "en": "Eph"},
    "11": {"de": "", "en": "Phil"},
    "12": {"de": "Kol", "en": "Col"},
    "13": {"de": "", "en": "1.Thess"},
    "14": {"de": "", "en": "2.Thess"},
    "15": {"de": "1.Tim", "en": "1.Tim"},
    "16": {"de": "", "en": "2.Tim"},
    "17": {"de": "", "en": "Titus"},
    "18": {"de": "", "en": "Philem"},
    "19": {"de": "", "en": "Heb"},
    "20": {"de": "Jak", "en": "James"},
    "21": {"de": "", "en": "1.Pet"},
    "22": {"de": "", "en": "2.Pet"},
    "23": {"de": "", "en": "1.John"},
    "24": {"de": "", "en": "2.John"},
    "25": {"de": "", "en": "3.John"},
    "26": {"de": "", "en": "Jude"},
    "27": {"de": "", "en": "Rev"},
}
